### ISSUE TITLE
[1.20.4] Butterfly texture is broken when client has CIT Resewn installed

### ISSUE THREAD

**Issue by Zekiu** [tomalbrc/toms-mobs#2]
Butterfly textures are broken when a client with CIT Resewn joins the server. Only some textures are broken. I don't know if you can fix this on your side, but I just wanted to let you know.

Client mod list:
- CIT Resewn
- Fabric API

Server mod list:
- Toms Mobs
- Polymer
- Fabric API

![2024-06-20_14 08 41](https://github.com/tomalbrc/toms-mobs/assets/68301723/4157f217-9ad0-4c49-b74e-5fa48202a18b)

![2024-06-20_14 15 40](https://github.com/tomalbrc/toms-mobs/assets/68301723/c3cb167c-7345-492b-b4a8-6b6604060e14)

**Comment by tomalbrc** [comment]
fixed in 2.1.2
