### ISSUE TITLE
Too Many Butterflies

### ISSUE THREAD

**Issue by lesxmore** [tomalbrc/toms-mobs#5]
There are too many butterflies within the world border, which is causing the server's TPS to drop, especially in the Jungle Biome. They also seem to be getting stuck at the border.
![354A7FD6-DA0C-4EA2-B579-12FEC1C8366C](https://github.com/user-attachments/assets/76751ee9-3af2-41bb-9669-b9bad14c792c)

**Comment by tomalbrc** [comment]
spawn rates were reduced now in 2.1.3
