### ISSUE TITLE
1.21.1 butterfly texture is replaced with horse armour

### ISSUE THREAD

**Issue by TazzerYT** [tomalbrc/toms-mobs#6]
on the 1.21.1 mod version the butterfly texture is replaced with different coloured horse armour.

**Comment by TazzerYT** [comment]
oh turns out all or most mobs are replaced with horse armour for some reason

**Comment by tomalbrc** [comment]
Try enabling autohost in the configs for polymer https://polymer.pb4.eu/latest/user/resource-pack-hosting/
Or use the resource pack in your servers folder, polymer/resource-pack.zip
